section_title:
  es: "Formación complementaria"
  en: "Professional Development"

items:
- id: "ai-docencia-2024"
  date: "2024-02-20/2024-03-05"
  skill: 
    es: "Inteligencia Artificial"
    en: "Artificial Intelligence"
  title: "Inteligencia Artificial aplicada a la docencia"
  metadata: |
    Universidad Autònoma de Barcelona
    Programa de Formación para la Mejora Docente
    Inteligencia Artificial
  description: "Curso sobre aplicaciones de IA en la docencia universitaria."
- id: "digital-publishing-2020"
  date: "2020-09-01/2020-12-15"
  skill: 
    es: "Edición Digital"
    en: "Digital Publishing"
  title: "Digital Publishing with Minimal Computing: humanities at a global scale (MITH 301)"
  metadata: |
    University of Maryland – MITH (USA)
    Universidad del Salvador (ARG)
    Curso de Postgrado
    Edición Digital
  description: "Edición mínima digital bilingüe de la 'Descripción de Buenos Aires' de Acarete du Biscay. Proyecto: https://dxvidmr.gitlab.io/the-voyagers-project/"
